import { Hero2 } from '@/widgets/hero2'

export default function Home() {
  return (
    <>
      <Hero2
        tagline="Create Next App"
        title="Generated by Next.js"
        description="Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora ipsam veritatis quibusdam quaerat ullam hic consequuntur architecto? Nesciunt, accusamus! Nemo cum est reiciendis laborum unde eos recusandae? Commodi, odio rerum!"
        actions={[
          { label: 'Get Started', url: 'https://nextjs.org/docs' },
          { label: 'GitHub', url: 'https://github.com', outlined: true },
        ]}
      />
    </>
  )
}
